dist: focal
sudo: false
language: python
python:
  - "3.9"
env:
  - PIP_DJANGO='Django~=3.1.9'
  - PIP_DJANGO='Django~=3.2.0'
install:
  - "pip install $PIP_DJANGO pyyaml coveralls pytest-django"
  - "pip install -e ."
script:
  coverage run $VIRTUAL_ENV/bin/py.test --ds=test_settings typedmodels/tests.py
after_success:
  coveralls
