sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - PIP_DJANGO='Django>=1.8,<1.9'
  - PIP_DJANGO='Django>=1.10,<1.11'
  - PIP_DJANGO='Django>=1.11,<1.12'
install:
  - "pip install $PIP_DJANGO"
  - "pip install pyyaml coveralls"
  - "pip install -e ."
script:
  coverage run runtests.py
after_success:
  coveralls
