sudo: false
language: python
python:
  - "3.6"
env:
  - PIP_DJANGO='Django>=2.2,<3.0'
  - PIP_DJANGO='Django>=3.0,<3.1'
install:
  - "pip install $PIP_DJANGO pyyaml coveralls pytest-django"
  - "pip install -e ."
script:
  coverage run $VIRTUAL_ENV/bin/py.test --ds=test_settings typedmodels/tests.py
after_success:
  coveralls
